a = input('Digite algo: ')
print('O tipo primitivo desse valor é: {}'.format(type(a)))
print('Só tem espaços? {}'.format(a.isspace()))
print('É um numero? {}'.format(a.isnumeric()))
print('É alfabetico? {}'.format(a.isalpha()))
print('É alphanumerico? {}'.format(a.isalnum()))
print('É um digito? {}'.format(a.isdigit()))
print('É um identificador ? {}'.format(a.isidentifier()))
print('É caixa baixa? {}'.format(a.islower()))
print('É caixa alta? {}'.format(a.isupper()))
print('É capitalizado? {}'.format(a.istitle()))
print(a.isprintable())
