dia = input('Que dia você Nasceu? (01): ')
mes = input('Que Mês você nasceu? (Jan): ')
ano = input('Que ano você nasce? (1900): ')
print('Você nasceu no dia ',dia,' de ', mes, ' de ', ano, '. Correto?')
print('Você nasceu no dia '+ dia + ' de ' + mes + ' de ' + ano + '. Correto?')
